"""同义词典数据（v0.4 手工策划；v0.9 扩容为数据文件加载）。

英文：`EN_SYNONYMS_RAW`（v0.2 主词典）+ `EN_SYNONYMS_EXTRA`（v0.4 扩充），
经 `embedder._build_stable_synonyms` 稳定化管线合并为最终词典。

中文：`ZH_SYNONYMS_RAW`，配合 `zh.ZhAdapter` 使用。

v0.9 词典扩容（exp_dict_expansion 实验定稿）：
    生产默认词典从手工策划小词典扩为「策划组 ∪ 词林/WordNet 大词典」，
    数据文件在 `src/aawm/data/{zh,en}_synonyms.json`（由
    experiments/gen_prod_dicts.py 生成）。GreenlistCodec 的默认词典
    走 `load_default_zh_dictionary()` / `load_default_en_dictionary()`；
    数据文件缺失时回退手工策划词典（保证最小可用）。
    实测收益（30 篇真实语料攻击谱，soft n>=1 匹配）：
      ZH: paws 27→30、s30 23→30、s50 12→23、存在性间隔 +7.6→+19.2
      EN: s30 28→29、s50 21→27、存在性间隔 +13.3→+42.0

词条设计原则：
1. 单词约束：英文词条必须是单个词（无空格/连字符），否则破坏 token 数；
   中文词条统一为双字词，配合前向最大匹配分词
2. 符号多样性：组内首字母（或声母）种类 ≥3，保证组在多数密钥映射下
   能表达双 bit（可锚定的动态判定为准）
3. 语义等价：组内词在常见语境可互换，不改变句意
4. 主词条唯一：同形词（动词/名词）只保留一个组，避免 dict 覆盖丢数据
"""
from __future__ import annotations

import json
import os
from typing import Dict, List, Optional

_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

_DEFAULT_ZH_CACHE: Optional[Dict[str, List[str]]] = None
_DEFAULT_EN_CACHE: Optional[Dict[str, List[str]]] = None


def _load_groups(filename: str) -> Optional[Dict[str, List[str]]]:
    """从数据文件加载 {组键: [词...]}；文件缺失返回 None。"""
    path = os.path.join(_DATA_DIR, filename)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        groups = json.load(f)
    return {f"g{i}": ws for i, ws in enumerate(groups)}


def load_default_zh_dictionary() -> Dict[str, List[str]]:
    """中文默认同义词典（策划组 ∪ 词林 '=' 严格同义组）。

    数据文件缺失时回退 ZH_SYNONYMS_RAW（手工策划小词典）。
    """
    global _DEFAULT_ZH_CACHE
    if _DEFAULT_ZH_CACHE is None:
        loaded = _load_groups("zh_synonyms.json")
        _DEFAULT_ZH_CACHE = loaded if loaded is not None else dict(ZH_SYNONYMS_RAW)
    return _DEFAULT_ZH_CACHE


def load_default_en_dictionary() -> Dict[str, List[str]]:
    """英文默认同义词典（策划组 ∪ WordNet synset >=3 单词组）。

    数据文件缺失时回退 EN_SYNONYMS_RAW + EN_SYNONYMS_EXTRA。
    """
    global _DEFAULT_EN_CACHE
    if _DEFAULT_EN_CACHE is None:
        loaded = _load_groups("en_synonyms.json")
        _DEFAULT_EN_CACHE = (
            loaded if loaded is not None
            else {**EN_SYNONYMS_RAW, **EN_SYNONYMS_EXTRA}
        )
    return _DEFAULT_EN_CACHE

# ---------------------------------------------------------------------------
# 英文原始词典（v0.2 的 _SYNONYMS_RAW 搬迁至此，内容不变）
# ---------------------------------------------------------------------------

EN_SYNONYMS_RAW: Dict[str, List[str]] = {
    # --- 形容词 ---
    "big": ["big", "large", "sizable", "substantial", "considerable"],
    "small": ["small", "minor", "modest", "compact", "slight", "tiny"],
    "good": ["good", "solid", "decent", "fine", "great", "excellent", "superb"],
    "bad": ["bad", "poor", "weak", "subpar", "inferior", "lousy", "awful"],
    "fast": ["fast", "quick", "rapid", "swift", "speedy", "brisk"],
    "slow": ["slow", "gradual", "unhurried", "sluggish", "leisurely", "lagging"],
    "important": ["important", "crucial", "critical", "vital", "essential", "significant"],
    "new": ["new", "fresh", "recent", "modern", "novel", "current"],
    "old": ["old", "prior", "earlier", "previous", "former", "aging"],
    "easy": ["easy", "simple", "straightforward", "effortless", "uncomplicated", "clear"],
    "hard": ["hard", "difficult", "tough", "challenging", "demanding", "tricky"],
    "happy": ["happy", "pleased", "glad", "delighted", "cheerful", "content"],
    "sad": ["sad", "unhappy", "down", "gloomy", "melancholy", "sorrowful"],
    "strong": ["strong", "powerful", "robust", "sturdy", "solid", "forceful"],
    "weak": ["weak", "fragile", "feeble", "flimsy", "frail", "faint"],
    "clear": ["clear", "obvious", "evident", "apparent", "plain", "distinct"],
    "strange": ["strange", "odd", "unusual", "peculiar", "bizarre", "curious"],
    "beautiful": ["beautiful", "lovely", "gorgeous", "stunning", "elegant", "radiant"],
    "bright": ["bright", "luminous", "vivid", "brilliant", "radiant", "shining"],
    "dark": ["dark", "dim", "murky", "shadowy", "gloomy", "obscure"],
    "safe": ["safe", "secure", "protected", "harmless", "sheltered", "sound"],
    "dangerous": ["dangerous", "risky", "hazardous", "perilous", "unsafe", "treacherous"],
    "common": ["common", "typical", "ordinary", "standard", "prevalent", "widespread"],
    "rare": ["rare", "scarce", "uncommon", "seldom", "infrequent", "unusual"],
    "simple": ["simple", "basic", "plain", "minimal", "unadorned", "spare"],
    "complex": ["complex", "intricate", "complicated", "elaborate", "sophisticated", "involved"],
    "modern": ["modern", "current", "contemporary", "recent", "present", "upgraded"],
    "ancient": ["ancient", "historic", "age", "traditional", "early", "original"],
    "cheap": ["cheap", "inexpensive", "affordable", "budget", "economical", "low"],
    "expensive": ["expensive", "costly", "pricey", "premium", "valuable", "lavish"],
    "quiet": ["quiet", "silent", "still", "calm", "peaceful", "tranquil"],
    "loud": ["loud", "noisy", "boisterous", "raucous", "thunderous", "vocal"],
    "warm": ["warm", "mild", "tepid", "pleasant", "balmy", "hot"],
    "cold": ["cold", "chilly", "frigid", "icy", "cool", "frosty"],
    "empty": ["empty", "vacant", "blank", "bare", "hollow", "vacuous"],
    "full": ["full", "complete", "entire", "whole", "packed", "total"],
    "very": ["very", "quite", "rather", "extremely", "highly", "deeply", "truly"],
    "really": ["really", "truly", "genuinely", "actually", "certainly", "surely"],
    "fully": ["fully", "completely", "entirely", "wholly", "totally", "thoroughly"],
    "quick": ["quick", "rapid", "swift", "speedy", "prompt", "immediate"],
    "major": ["major", "primary", "principal", "leading", "central", "significant"],
    "minor": ["minor", "small", "secondary", "lesser", "marginal", "trivial"],
    "key": ["key", "central", "core", "primary", "crucial", "pivotal"],
    "final": ["final", "last", "closing", "concluding", "ultimate", "terminal"],
    "initial": ["initial", "first", "opening", "original", "early", "starting"],
    "similar": ["similar", "comparable", "alike", "analogous", "related", "matching"],
    "different": ["different", "distinct", "varied", "diverse", "dissimilar", "unique"],
    "possible": ["possible", "feasible", "viable", "achievable", "practical", "doable"],
    "necessary": ["necessary", "essential", "required", "needed", "vital", "imperative"],
    "useful": ["useful", "helpful", "valuable", "practical", "handy", "beneficial"],
    "popular": ["popular", "widespread", "favorite", "mainstream", "trendy", "prominent"],
    # --- 动词 ---
    "show": ["show", "display", "present", "reveal", "demonstrate", "exhibit"],
    "use": ["use", "utilize", "employ", "apply", "leverage", "adopt"],
    "make": ["make", "create", "produce", "build", "generate", "craft"],
    "build": ["build", "construct", "assemble", "create", "develop", "fabricate"],
    "start": ["start", "begin", "commence", "initiate", "launch", "open"],
    "end": ["end", "conclude", "finish", "terminate", "complete", "close"],
    "help": ["help", "assist", "aid", "support", "facilitate", "serve"],
    "improve": ["improve", "enhance", "refine", "upgrade", "optimize", "strengthen"],
    "reduce": ["reduce", "lower", "decrease", "diminish", "lessen", "compress"],
    "increase": ["increase", "raise", "grow", "expand", "boost", "amplify"],
    "change": ["change", "modify", "alter", "adjust", "transform", "revise"],
    "keep": ["keep", "retain", "maintain", "preserve", "hold", "sustain"],
    "remove": ["remove", "eliminate", "delete", "strip", "erase", "withdraw"],
    "add": ["add", "append", "attach", "include", "insert", "incorporate"],
    "find": ["find", "discover", "locate", "identify", "detect", "uncover"],
    "tell": ["tell", "inform", "notify", "advise", "brief", "alert"],
    "ask": ["ask", "inquire", "request", "query", "question", "consult"],
    "answer": ["answer", "reply", "respond", "address", "resolve", "counter"],
    "think": ["think", "believe", "consider", "reckon", "suppose", "judge"],
    "need": ["need", "require", "want", "demand", "involve", "necessitate"],
    "get": ["get", "obtain", "acquire", "receive", "gain", "secure"],
    "give": ["give", "provide", "offer", "supply", "deliver", "grant"],
    "take": ["take", "grab", "seize", "capture", "obtain", "claim"],
    "try": ["try", "attempt", "endeavor", "strive", "aim", "seek"],
    "allow": ["allow", "permit", "enable", "authorize", "sanction", "approve"],
    "prevent": ["prevent", "stop", "block", "avert", "hinder", "prohibit"],
    "cause": ["cause", "trigger", "produce", "generate", "prompt", "evoke"],
    "create": ["create", "produce", "generate", "form", "establish", "craft"],
    "explain": ["explain", "clarify", "describe", "detail", "elaborate", "outline"],
    "suggest": ["suggest", "recommend", "propose", "advise", "counsel", "submit"],
    "confirm": ["confirm", "verify", "validate", "corroborate", "authenticate", "certify"],
    "check": ["check", "verify", "inspect", "examine", "review", "audit"],
    "test": ["test", "evaluate", "assess", "trial", "probe", "benchmark"],
    "send": ["send", "transmit", "dispatch", "forward", "relay", "post"],
    "receive": ["receive", "get", "obtain", "accept", "collect", "retrieve"],
    "deploy": ["deploy", "launch", "release", "ship", "rollout", "distribute"],
    "run": ["run", "execute", "operate", "perform", "process", "handle"],
    "learn": ["learn", "study", "master", "grasp", "acquire", "absorb"],
    "teach": ["teach", "instruct", "educate", "train", "tutor", "school"],
    "write": ["write", "compose", "draft", "author", "pen", "record"],
    "read": ["read", "review", "peruse", "examine", "study", "scan"],
    "choose": ["choose", "select", "pick", "prefer", "nominate", "favor"],
    "decide": ["decide", "determine", "resolve", "conclude", "settle", "rule"],
    "plan": ["plan", "design", "devise", "formulate", "map", "arrange"],
    "manage": ["manage", "handle", "oversee", "administer", "coordinate", "direct"],
    "handle": ["handle", "manage", "address", "treat", "process", "field"],
    "solve": ["solve", "resolve", "fix", "settle", "untangle", "repair"],
    "fix": ["fix", "repair", "mend", "patch", "correct", "rectify"],
    "break": ["break", "crack", "fracture", "shatter", "rupture", "split"],
    "open": ["open", "unlock", "launch", "unveil", "reveal", "initiate", "unbolt"],
    "close": ["close", "shut", "seal", "conclude", "finish", "terminate"],
    "buy": ["buy", "purchase", "acquire", "procure", "obtain", "secure"],
    "sell": ["sell", "market", "trade", "vend", "move", "auction"],
    "work": ["work", "function", "operate", "perform", "behave", "process"],
    "support": ["support", "back", "assist", "bolster", "sponsor", "underpin"],
    "expect": ["expect", "anticipate", "await", "predict", "foresee", "envision"],
    "prefer": ["prefer", "favor", "lean", "opt", "select", "choose"],
    "consider": ["consider", "weigh", "evaluate", "examine", "contemplate", "review"],
    # --- 名词 ---
    "system": ["system", "platform", "framework", "infrastructure", "architecture", "setup"],
    "platform": ["platform", "system", "framework", "environment", "infrastructure", "base"],
    "framework": ["framework", "platform", "system", "structure", "skeleton", "layout"],
    "product": ["product", "offering", "item", "goods", "artifact", "release"],
    "service": ["service", "offering", "solution", "capability", "facility", "operation"],
    "feature": ["feature", "capability", "function", "characteristic", "attribute", "trait"],
    "user": ["user", "customer", "client", "member", "account", "patron"],
    "customer": ["customer", "client", "user", "buyer", "patron", "shopper"],
    "team": ["team", "group", "crew", "squad", "unit", "staff"],
    "company": ["company", "firm", "business", "enterprise", "organization", "venture"],
    "project": ["project", "initiative", "endeavor", "venture", "undertaking", "campaign"],
    "task": ["task", "job", "assignment", "chore", "duty", "mission"],
    "goal": ["goal", "objective", "target", "aim", "ambition", "purpose"],
    "result": ["result", "outcome", "conclusion", "finding", "upshot", "product"],
    "process": ["process", "procedure", "workflow", "method", "routine", "pipeline"],
    "method": ["method", "approach", "technique", "procedure", "strategy", "tactic"],
    "idea": ["idea", "concept", "notion", "thought", "conception", "insight"],
    "problem": ["problem", "issue", "challenge", "difficulty", "obstacle", "hurdle"],
    "solution": ["solution", "remedy", "fix", "answer", "resolution", "cure"],
    "question": ["question", "query", "inquiry", "issue", "matter", "concern"],
    "reason": ["reason", "cause", "rationale", "motive", "justification", "basis"],
    "example": ["example", "instance", "case", "sample", "illustration", "specimen"],
    "data": ["data", "information", "records", "figures", "statistics", "evidence"],
    "information": ["information", "data", "details", "facts", "knowledge", "intelligence"],
    "report": ["report", "document", "summary", "account", "analysis", "writeup"],
    "document": ["document", "file", "record", "paper", "artifact", "text"],
    "message": ["message", "note", "communication", "correspondence", "memo", "dispatch"],
    "request": ["request", "ask", "petition", "appeal", "requisition", "query"],
    "response": ["response", "reply", "answer", "reaction", "feedback", "return"],
    "feedback": ["feedback", "input", "comments", "response", "critique", "observations"],
    "update": ["update", "revision", "refresh", "amendment", "modification", "upgrade"],
    "version": ["version", "release", "edition", "iteration", "revision", "variant"],
    "release": ["release", "launch", "edition", "version", "debut", "rollout"],
    "issue": ["issue", "problem", "defect", "flaw", "glitch", "trouble"],
    "bug": ["bug", "defect", "flaw", "glitch", "fault", "error"],
    "error": ["error", "mistake", "fault", "bug", "slip", "blunder"],
    "risk": ["risk", "danger", "threat", "hazard", "exposure", "peril"],
    "benefit": ["benefit", "advantage", "gain", "upside", "value", "payoff"],
    "cost": ["cost", "expense", "price", "outlay", "expenditure", "charge"],
    "value": ["value", "worth", "merit", "usefulness", "significance", "weight"],
    "quality": ["quality", "caliber", "grade", "standard", "excellence", "class"],
    "speed": ["speed", "pace", "velocity", "rate", "tempo", "quickness"],
    "time": ["time", "period", "duration", "span", "interval", "stretch"],
    "place": ["place", "location", "spot", "site", "position", "venue"],
    "person": ["person", "individual", "someone", "figure", "party", "human"],
    "people": ["people", "individuals", "persons", "folks", "workers", "humans"],
    "way": ["way", "method", "approach", "manner", "means", "route"],
    "part": ["part", "portion", "segment", "section", "component", "piece"],
    "number": ["number", "count", "quantity", "total", "figure", "sum"],
    "level": ["level", "degree", "extent", "grade", "tier", "amount"],
    "kind": ["kind", "type", "sort", "variety", "category", "class"],
    "type": ["type", "kind", "sort", "category", "class", "variety"],
    "area": ["area", "region", "zone", "district", "sector", "domain"],
    "field": ["field", "domain", "area", "discipline", "sphere", "realm"],
    "world": ["world", "globe", "planet", "earth", "society", "humanity"],
    "future": ["future", "horizon", "prospect", "tomorrow", "outlook", "years"],
    "past": ["past", "history", "background", "record", "earlier", "heritage"],
    "growth": ["growth", "expansion", "increase", "rise", "development", "gain"],
    "language": ["language", "tongue", "speech", "dialect", "vernacular", "wording"],
    "network": ["network", "web", "grid", "mesh", "system", "nexus"],
    "engine": ["engine", "motor", "core", "mechanism", "powerhouse", "system"],
    "model": ["model", "pattern", "template", "blueprint", "prototype", "design"],
    "tool": ["tool", "instrument", "utility", "device", "implement", "appliance"],
    "device": ["device", "gadget", "appliance", "machine", "instrument", "unit"],
    "machine": ["machine", "device", "apparatus", "system", "engine", "mechanism"],
    "security": ["security", "protection", "safety", "defense", "shielding", "safeguarding"],
    "performance": ["performance", "speed", "efficiency", "throughput", "responsiveness", "output"],
    "experience": ["experience", "exposure", "familiarity", "background", "knowledge", "practice"],
    "environment": ["environment", "setting", "surroundings", "context", "habitat", "milieu"],
    "structure": ["structure", "layout", "design", "arrangement", "organization", "blueprint"],
    "purpose": ["purpose", "aim", "intent", "objective", "mission", "rationale"],
    "detail": ["detail", "particular", "specific", "element", "aspect", "facet"],
    "review": ["review", "assessment", "evaluation", "examination", "audit", "analysis"],
    "analysis": ["analysis", "examination", "study", "assessment", "evaluation", "review"],
    "budget": ["budget", "allocation", "allowance", "funds", "resources", "finances"],
    "progress": ["progress", "advancement", "headway", "development", "stride", "momentum"],
    "insight": ["insight", "understanding", "perception", "awareness", "discernment", "intuition"],
    "pattern": ["pattern", "trend", "model", "design", "motif", "template"],
    "option": ["option", "choice", "alternative", "possibility", "variant", "candidate"],
}

# ---------------------------------------------------------------------------
# 英文扩充词典（v0.4 新增，~280 组高频词）
# 设计注意：
# - 主词条不与 RAW 重复（"language" 等已排除）
# - 同形词（动词/名词）只建一个组
# - 与 RAW 组共享的候选词由稳定化管线自动归属（跨组词归首组）
# ---------------------------------------------------------------------------

EN_SYNONYMS_EXTRA: Dict[str, List[str]] = {
    # --- 形容词（扩充） ---
    "able": ["able", "capable", "competent", "skilled"],
    "accurate": ["accurate", "precise", "exact", "correct"],
    "active": ["active", "busy", "engaged", "involved"],
    "amazing": ["amazing", "stunning", "incredible", "remarkable"],
    "angry": ["angry", "mad", "furious", "irate"],
    "aware": ["aware", "conscious", "mindful", "alert"],
    "basic": ["basic", "fundamental", "elementary", "rudimentary"],
    "calm": ["calm", "composed", "serene", "unruffled"],
    "careful": ["careful", "cautious", "meticulous", "prudent"],
    "clean": ["clean", "tidy", "neat", "immaculate"],
    "comfortable": ["comfortable", "cozy", "snug", "pleasant"],
    "complete": ["complete", "total", "entire", "thorough"],
    "confident": ["confident", "assured", "certain", "positive"],
    "curious": ["curious", "inquisitive", "eager", "attentive"],
    "deep": ["deep", "profound", "intense", "vast"],
    "delicate": ["delicate", "fine", "subtle", "fragile"],
    "dense": ["dense", "thick", "packed", "crowded"],
    "direct": ["direct", "straightforward", "frank", "candid"],
    "dirty": ["dirty", "soiled", "messy", "grimy"],
    "dry": ["dry", "arid", "parched", "dehydrated"],
    "eager": ["eager", "keen", "enthusiastic", "avid"],
    "efficient": ["efficient", "effective", "productive", "streamlined"],
    "excited": ["excited", "thrilled", "elated", "animated"],
    "famous": ["famous", "renowned", "notable", "celebrated"],
    "familiar": ["familiar", "known", "recognized", "acquainted"],
    "flexible": ["flexible", "adaptable", "versatile", "pliable"],
    "formal": ["formal", "official", "proper", "ceremonial"],
    "free": ["free", "liberated", "unrestricted", "open"],
    "frequent": ["frequent", "regular", "repeated", "constant"],
    "friendly": ["friendly", "amiable", "cordial", "genial"],
    "generous": ["generous", "giving", "liberal", "bountiful"],
    "gentle": ["gentle", "mild", "tender", "soothing"],
    "genuine": ["genuine", "authentic", "real", "sincere"],
    "huge": ["huge", "enormous", "massive", "gigantic"],
    "humble": ["humble", "modest", "unassuming", "meek"],
    "ideal": ["ideal", "perfect", "optimal", "excellent"],
    "intelligent": ["intelligent", "smart", "clever", "brilliant"],
    "interesting": ["interesting", "intriguing", "engaging", "fascinating"],
    "lazy": ["lazy", "idle", "unmotivated", "slack"],
    "legal": ["legal", "lawful", "legitimate", "authorized"],
    "likely": ["likely", "probable", "expected", "anticipated"],
    "lucky": ["lucky", "fortunate", "blessed", "favored"],
    "mature": ["mature", "developed", "ripe", "seasoned"],
    "nervous": ["nervous", "anxious", "tense", "apprehensive"],
    "nice": ["nice", "pleasant", "agreeable", "delightful"],
    "patient": ["patient", "tolerant", "forbearing", "unhurried"],
    "perfect": ["perfect", "flawless", "impeccable", "ideal"],
    "polite": ["polite", "courteous", "respectful", "mannerly"],
    "proud": ["proud", "pleased", "satisfied", "honored"],
    "ready": ["ready", "prepared", "set", "equipped"],
    "real": ["real", "actual", "genuine", "true"],
    "reliable": ["reliable", "dependable", "trustworthy", "steady"],
    "rich": ["rich", "wealthy", "affluent", "prosperous"],
    "rough": ["rough", "coarse", "uneven", "jagged"],
    "rude": ["rude", "impolite", "discourteous", "insolent"],
    "serious": ["serious", "earnest", "grave", "solemn"],
    "sharp": ["sharp", "keen", "acute", "pointed"],
    "shy": ["shy", "timid", "reserved", "bashful"],
    "sick": ["sick", "ill", "unwell", "ailing"],
    "smooth": ["smooth", "even", "level", "flat"],
    "soft": ["soft", "tender", "supple", "yielding"],
    "stable": ["stable", "steady", "secure", "balanced"],
    "strict": ["strict", "rigid", "exacting", "stringent"],
    "successful": ["successful", "prosperous", "triumphant", "victorious"],
    "tall": ["tall", "high", "lofty", "soaring"],
    "thin": ["thin", "slim", "slender", "slight"],
    "tired": ["tired", "weary", "exhausted", "fatigued"],
    "true": ["true", "accurate", "correct", "factual"],
    "ugly": ["ugly", "unattractive", "hideous", "unsightly"],
    "unique": ["unique", "distinctive", "singular", "exceptional"],
    "vast": ["vast", "expansive", "immense", "boundless"],
    "wet": ["wet", "damp", "moist", "soaked"],
    "willing": ["willing", "ready", "inclined", "disposed"],
    "wise": ["wise", "sage", "prudent", "judicious"],
    "wonderful": ["wonderful", "marvelous", "amazing", "wondrous"],
    # --- 动词（扩充） ---
    "accept": ["accept", "receive", "approve", "embrace"],
    "achieve": ["achieve", "attain", "reach", "accomplish"],
    "admit": ["admit", "confess", "acknowledge", "disclose"],
    "agree": ["agree", "concur", "accede", "consent"],
    "appear": ["appear", "seem", "look", "emerge"],
    "argue": ["argue", "debate", "dispute", "contend"],
    "arrange": ["arrange", "organize", "order", "coordinate"],
    "arrive": ["arrive", "reach", "land", "enter"],
    "avoid": ["avoid", "evade", "dodge", "shun"],
    "become": ["become", "grow", "turn", "develop"],
    "call": ["call", "name", "label", "designate"],
    "carry": ["carry", "bear", "transport", "convey"],
    "catch": ["catch", "capture", "seize", "snare"],
    "celebrate": ["celebrate", "commemorate", "honor", "observe"],
    "compare": ["compare", "contrast", "evaluate", "benchmark", "weigh", "match"],
    "compete": ["compete", "contend", "vie", "rival"],
    "complain": ["complain", "grumble", "protest", "gripe"],
    "concentrate": ["concentrate", "focus", "attend", "center"],
    "connect": ["connect", "join", "link", "attach"],
    "contain": ["contain", "include", "hold", "encompass"],
    "continue": ["continue", "persist", "endure", "proceed"],
    "control": ["control", "regulate", "govern", "direct"],
    "convince": ["convince", "persuade", "assure", "sway"],
    "count": ["count", "tally", "number", "calculate"],
    "cut": ["cut", "slice", "trim", "sever"],
    "damage": ["damage", "harm", "impair", "injure"],
    "define": ["define", "specify", "delineate", "describe"],
    "deliver": ["deliver", "bring", "transport", "convey"],
    "desire": ["desire", "want", "wish", "crave"],
    "destroy": ["destroy", "demolish", "wreck", "ruin"],
    "develop": ["develop", "evolve", "advance", "progress"],
    "disappear": ["disappear", "vanish", "fade", "evaporate"],
    "discuss": ["discuss", "debate", "review", "confer"],
    "dislike": ["dislike", "hate", "detest", "loathe"],
    "distribute": ["distribute", "spread", "disburse", "allocate"],
    "divide": ["divide", "split", "separate", "partition"],
    "draw": ["draw", "sketch", "illustrate", "draft"],
    "drive": ["drive", "operate", "pilot", "steer"],
    "drop": ["drop", "fall", "descend", "plunge"],
    "earn": ["earn", "gain", "win", "merit"],
    "eat": ["eat", "dine", "consume", "devour"],
    "enter": ["enter", "join", "cross", "penetrate"],
    "fail": ["fail", "flop", "miss", "founder"],
    "fear": ["fear", "dread", "tremble", "cower"],
    "feel": ["feel", "sense", "perceive", "experience"],
    "fight": ["fight", "battle", "clash", "combat"],
    "fill": ["fill", "load", "pack", "stuff"],
    "fit": ["fit", "suit", "match", "become"],
    "float": ["float", "drift", "bob", "hover"],
    "fly": ["fly", "soar", "glide", "hover"],
    "follow": ["follow", "pursue", "trace", "chase"],
    "forget": ["forget", "omit", "overlook", "neglect"],
    "forgive": ["forgive", "pardon", "excuse", "acquit"],
    "gather": ["gather", "collect", "accumulate", "muster"],
    "guard": ["guard", "defend", "shield", "safeguard"],
    "hear": ["hear", "listen", "overhear", "attend"],
    "hide": ["hide", "conceal", "cache", "camouflage"],
    "hire": ["hire", "employ", "recruit", "engage"],
    "hold": ["hold", "grasp", "grip", "clutch"],
    "hope": ["hope", "wish", "aspire", "yearn"],
    "hunt": ["hunt", "seek", "pursue", "scour"],
    "hurry": ["hurry", "rush", "dash", "scramble"],
    "ignore": ["ignore", "disregard", "overlook", "neglect"],
    "imagine": ["imagine", "envision", "visualize", "picture"],
    "include": ["include", "contain", "encompass", "comprise"],
    "insist": ["insist", "demand", "press", "urge"],
    "intend": ["intend", "plan", "mean", "design"],
    "invite": ["invite", "summon", "ask", "welcome"],
    "jump": ["jump", "leap", "spring", "hop"],
    "know": ["know", "understand", "grasp", "realize"],
    "lack": ["lack", "want", "miss", "require"],
    "laugh": ["laugh", "chuckle", "giggle", "snicker"],
    "lead": ["lead", "guide", "direct", "head"],
    "leave": ["leave", "depart", "exit", "vacate"],
    "lift": ["lift", "raise", "elevate", "hoist"],
    "live": ["live", "reside", "dwell", "inhabit"],
    "look": ["look", "gaze", "glance", "peer"],
    "lose": ["lose", "misplace", "drop", "forfeit"],
    "love": ["love", "adore", "cherish", "treasure"],
    "mark": ["mark", "label", "tag", "designate"],
    "mean": ["mean", "signify", "intend", "convey"],
    "measure": ["measure", "gauge", "quantify", "assess"],
    "meet": ["meet", "encounter", "confront", "convene"],
    "mention": ["mention", "note", "cite", "reference"],
    "miss": ["miss", "skip", "forfeit", "overlook"],
    "move": ["move", "shift", "relocate", "budge"],
    "notice": ["notice", "observe", "spot", "behold"],
    "organize": ["organize", "arrange", "order", "coordinate", "sort", "marshal"],
    "own": ["own", "possess", "hold", "have"],
    "pass": ["pass", "succeed", "qualify", "advance"],
    "pay": ["pay", "compensate", "remunerate", "reimburse"],
    "point": ["point", "indicate", "gesture", "signal"],
    "praise": ["praise", "compliment", "applaud", "laud"],
    "prepare": ["prepare", "ready", "arrange", "equip"],
    "pretend": ["pretend", "feign", "act", "fake"],
    "print": ["print", "publish", "issue", "release", "reproduce", "output"],
    "promise": ["promise", "vow", "pledge", "swear"],
    "protect": ["protect", "guard", "shield", "defend"],
    "pull": ["pull", "tug", "drag", "haul"],
    "push": ["push", "press", "shove", "nudge"],
    "put": ["put", "place", "set", "lay"],
    "realize": ["realize", "grasp", "understand", "achieve"],
    "recall": ["recall", "remember", "recollect", "retrieve", "reminisce", "evoke"],
    "refuse": ["refuse", "reject", "decline", "deny"],
    "regard": ["regard", "consider", "view", "deem"],
    "regret": ["regret", "rue", "lament", "mourn"],
    "relax": ["relax", "unwind", "rest", "decompress"],
    "remain": ["remain", "stay", "linger", "abide"],
    "remind": ["remind", "prompt", "jog", "cue"],
    "repeat": ["repeat", "reiterate", "restate", "echo"],
    "resemble": ["resemble", "mirror", "approximate", "parallel"],
    "rest": ["rest", "relax", "repose", "refresh"],
    "ride": ["ride", "drive", "travel", "journey"],
    "roll": ["roll", "tumble", "spin", "rotate"],
    "rule": ["rule", "govern", "control", "regulate"],
    "satisfy": ["satisfy", "please", "gratify", "fulfill"],
    "say": ["say", "state", "mention", "voice"],
    "scare": ["scare", "frighten", "spook", "terrify"],
    "search": ["search", "seek", "hunt", "scour"],
    "see": ["see", "view", "watch", "behold"],
    "shake": ["shake", "tremble", "quiver", "quake"],
    "share": ["share", "divide", "distribute", "partition"],
    "shine": ["shine", "glow", "sparkle", "gleam"],
    "shout": ["shout", "yell", "cry", "holler"],
    "sleep": ["sleep", "doze", "snooze", "slumber"],
    "speak": ["speak", "talk", "converse", "utter"],
    "spend": ["spend", "exhaust", "consume", "deplete"],
    "stretch": ["stretch", "extend", "elongate", "lengthen"],
    "strike": ["strike", "hit", "slap", "smack"],
    "suffer": ["suffer", "endure", "bear", "undergo"],
    "surprise": ["surprise", "astonish", "amaze", "startle"],
    "survive": ["survive", "endure", "weather", "outlast"],
    "steal": ["steal", "pilfer", "swipe", "snatch"],
    "talk": ["talk", "speak", "converse", "chat"],
    "tend": ["tend", "incline", "lean", "gravitate"],
    "thank": ["thank", "gratify", "appreciate", "acknowledge"],
    "throw": ["throw", "hurl", "fling", "pitch"],
    "touch": ["touch", "feel", "brush", "contact"],
    "travel": ["travel", "journey", "tour", "roam"],
    "trust": ["trust", "believe", "rely", "confide"],
    "turn": ["turn", "rotate", "spin", "pivot"],
    "understand": ["understand", "comprehend", "grasp", "fathom"],
    "visit": ["visit", "tour", "see", "explore"],
    "wait": ["wait", "linger", "stay", "pause"],
    "wake": ["wake", "awaken", "arouse", "stir"],
    "walk": ["walk", "stroll", "amble", "stride"],
    "warn": ["warn", "alert", "caution", "forewarn"],
    "wash": ["wash", "clean", "rinse", "cleanse"],
    "wear": ["wear", "don", "sport", "flaunt"],
    "win": ["win", "earn", "gain", "triumph"],
    "wonder": ["wonder", "marvel", "speculate", "ponder"],
    "worry": ["worry", "fret", "stew", "fuss"],
    # --- 名词（扩充） ---
    "action": ["action", "deed", "endeavor", "undertaking"],
    "advice": ["advice", "counsel", "guidance", "direction"],
    "agreement": ["agreement", "accord", "pact", "contract"],
    "animal": ["animal", "creature", "beast", "fauna"],
    "anxiety": ["anxiety", "worry", "fear", "unease"],
    "appearance": ["appearance", "look", "aspect", "presentation"],
    "argument": ["argument", "dispute", "quarrel", "debate"],
    "article": ["article", "piece", "story", "feature"],
    "artist": ["artist", "creator", "maker", "designer"],
    "attack": ["attack", "assault", "strike", "offensive"],
    "attitude": ["attitude", "outlook", "stance", "posture"],
    "audience": ["audience", "crowd", "viewers", "public"],
    "author": ["author", "writer", "creator", "composer"],
    "authority": ["authority", "power", "control", "dominion"],
    "balance": ["balance", "equilibrium", "stability", "poise"],
    "bird": ["bird", "fowl", "avian", "songbird"],
    "birth": ["birth", "origin", "start", "beginning"],
    "block": ["block", "section", "segment", "chunk"],
    "boat": ["boat", "vessel", "craft", "ship"],
    "book": ["book", "volume", "publication", "edition"],
    "boss": ["boss", "manager", "supervisor", "chief"],
    "box": ["box", "container", "crate", "case"],
    "boy": ["boy", "lad", "youngster", "youth"],
    "brain": ["brain", "mind", "intellect", "psyche"],
    "bridge": ["bridge", "link", "connector", "span"],
    "brother": ["brother", "sibling", "kin", "relation"],
    "building": ["building", "structure", "edifice", "premises"],
    "car": ["car", "auto", "vehicle", "automobile"],
    "cat": ["cat", "feline", "kitty", "tomcat"],
    "cave": ["cave", "cavern", "grotto", "hollow"],
    "chance": ["chance", "opportunity", "likelihood", "probability"],
    "chapter": ["chapter", "section", "division", "installment"],
    "character": ["character", "nature", "temperament", "disposition"],
    "chart": ["chart", "graph", "plot", "diagram"],
    "child": ["child", "kid", "youngster", "minor"],
    "city": ["city", "town", "municipality", "metropolis"],
    "clothes": ["clothes", "clothing", "garments", "attire"],
    "cloud": ["cloud", "haze", "mist", "vapor"],
    "coast": ["coast", "shore", "beach", "seaboard"],
    "college": ["college", "university", "school", "institution"],
    "color": ["color", "shade", "tint", "hue"],
    "comfort": ["comfort", "ease", "relief", "consolation"],
    "comment": ["comment", "remark", "observation", "statement"],
    "committee": ["committee", "board", "panel", "council"],
    "community": ["community", "society", "neighborhood", "populace"],
    "competition": ["competition", "contest", "rivalry", "tournament"],
    "complaint": ["complaint", "grievance", "protest", "objection"],
    "computer": ["computer", "machine", "workstation", "calculator"],
    "connection": ["connection", "link", "bond", "tie"],
    "contract": ["contract", "agreement", "deal", "pact"],
    "copy": ["copy", "duplicate", "replica", "facsimile"],
    "corner": ["corner", "bend", "angle", "junction"],
    "country": ["country", "nation", "state", "land"],
    "couple": ["couple", "pair", "duo", "twosome"],
    "cow": ["cow", "cattle", "bovine", "livestock"],
    "crack": ["crack", "fissure", "crevice", "fracture"],
    "crash": ["crash", "collision", "wreck", "impact"],
    "crisis": ["crisis", "emergency", "catastrophe", "turmoil"],
    "crowd": ["crowd", "throng", "mob", "masses"],
    "cup": ["cup", "mug", "vessel", "container"],
    "current": ["current", "present", "flow", "stream"],
    "curve": ["curve", "bend", "arc", "arch"],
    "custom": ["custom", "tradition", "practice", "convention"],
    "dad": ["dad", "papa", "pa", "pop"],
    "deal": ["deal", "transaction", "bargain", "arrangement"],
    "death": ["death", "demise", "passing", "mortality"],
    "decision": ["decision", "verdict", "ruling", "judgment"],
    "delay": ["delay", "postponement", "wait", "holdup"],
    "departure": ["departure", "exit", "leave", "withdrawal"],
    "description": ["description", "account", "picture", "portrait"],
    "difference": ["difference", "distinction", "disparity", "contrast", "variance", "gap"],
    "dinner": ["dinner", "meal", "supper", "banquet"],
    "direction": ["direction", "heading", "bearing", "orientation"],
    "director": ["director", "chief", "head", "leader"],
    "disaster": ["disaster", "catastrophe", "calamity", "tragedy"],
    "discussion": ["discussion", "dialogue", "conversation", "debate"],
    "disease": ["disease", "illness", "ailment", "sickness"],
    "display": ["display", "screen", "monitor", "panel"],
    "distance": ["distance", "length", "span", "gap"],
    "doctor": ["doctor", "physician", "medic", "practitioner"],
    "dog": ["dog", "hound", "canine", "pooch"],
    "door": ["door", "gate", "entry", "portal"],
    "drawing": ["drawing", "sketch", "illustration", "rendering"],
    "dream": ["dream", "fantasy", "vision", "aspiration"],
    "driver": ["driver", "operator", "wheelman", "chauffeur"],
    "duty": ["duty", "obligation", "burden", "assignment"],
    "effect": ["effect", "impact", "consequence", "aftermath"],
    "effort": ["effort", "attempt", "striving", "labor"],
    "employee": ["employee", "worker", "staffer", "hand"],
    "enemy": ["enemy", "foe", "adversary", "opponent"],
    "energy": ["energy", "vigor", "stamina", "vitality"],
    "event": ["event", "incident", "occurrence", "happening"],
    "exam": ["exam", "test", "quiz", "assessment"],
    "explanation": ["explanation", "account", "reasoning", "clarification"],
    "expression": ["expression", "phrase", "utterance", "wording"],
    "extension": ["extension", "expansion", "prolongation", "addition"],
    "extent": ["extent", "degree", "scope", "range"],
    "fact": ["fact", "reality", "truth", "verity"],
    "failure": ["failure", "collapse", "defeat", "breakdown"],
    "family": ["family", "household", "kin", "relatives"],
    "farmer": ["farmer", "grower", "agriculturist", "tiller"],
    "father": ["father", "dad", "papa", "sire"],
    "feeling": ["feeling", "emotion", "sentiment", "sensation"],
    "fiction": ["fiction", "novel", "story", "narrative"],
    "film": ["film", "movie", "picture", "cinema"],
    "fire": ["fire", "blaze", "flame", "inferno"],
    "flower": ["flower", "blossom", "bloom", "floret"],
    "food": ["food", "meal", "nourishment", "sustenance"],
    "forest": ["forest", "woods", "woodland", "grove"],
    "form": ["form", "shape", "format", "configuration"],
    "friend": ["friend", "companion", "buddy", "pal"],
    "fun": ["fun", "enjoyment", "amusement", "merriment"],
    "game": ["game", "match", "contest", "competition"],
    "garden": ["garden", "yard", "lawn", "plot"],
    "gift": ["gift", "present", "offering", "token"],
    "girl": ["girl", "lass", "maiden", "miss"],
    "government": ["government", "administration", "regime", "authority"],
    "grandfather": ["grandfather", "grandpa", "elder", "ancestor"],
    "guest": ["guest", "visitor", "caller", "attendee"],
    "guy": ["guy", "fellow", "man", "chap"],
    "hardware": ["hardware", "equipment", "gear", "machinery"],
    "hole": ["hole", "gap", "opening", "cavity"],
    "holiday": ["holiday", "vacation", "break", "recess"],
    "home": ["home", "house", "residence", "dwelling"],
    "hotel": ["hotel", "inn", "lodge", "hostelry"],
    "hobby": ["hobby", "pastime", "avocation", "diversion"],
    "image": ["image", "picture", "photo", "visual"],
    "influence": ["influence", "impact", "sway", "clout"],
    "injury": ["injury", "harm", "wound", "trauma"],
    "insect": ["insect", "beetle", "critter", "vermin"],
    "instruction": ["instruction", "direction", "guidance", "teaching"],
    "interest": ["interest", "fascination", "curiosity", "appeal"],
    "introduction": ["introduction", "preface", "foreword", "opening"],
    "item": ["item", "object", "article", "artifact"],
    "journey": ["journey", "trip", "voyage", "expedition"],
    "joy": ["joy", "delight", "pleasure", "elation"],
    "judge": ["judge", "magistrate", "justice", "arbiter"],
    "knowledge": ["knowledge", "expertise", "scholarship", "erudition"],
    "law": ["law", "rule", "statute", "regulation"],
    "leader": ["leader", "chief", "head", "principal"],
    "lesson": ["lesson", "class", "session", "lecture"],
    "life": ["life", "existence", "living", "lifetime"],
    "light": ["light", "illumination", "lamp", "glow"],
    "limit": ["limit", "restriction", "cap", "ceiling"],
    "line": ["line", "row", "queue", "string"],
    "list": ["list", "inventory", "roster", "catalog"],
    "load": ["load", "burden", "weight", "cargo"],
    "magazine": ["magazine", "periodical", "journal", "publication"],
    "maintenance": ["maintenance", "upkeep", "servicing", "repair"],
    "man": ["man", "male", "gentleman", "fellow"],
    "market": ["market", "marketplace", "trade", "commerce"],
    "memory": ["memory", "recollection", "remembrance", "recall"],
    "middle": ["middle", "center", "midpoint", "heart"],
    "moment": ["moment", "instant", "second", "flash"],
    "money": ["money", "cash", "currency", "finances"],
    "mood": ["mood", "temper", "spirit", "disposition"],
    "mother": ["mother", "mom", "mama", "parent"],
    "mountain": ["mountain", "peak", "summit", "ridge"],
    "movie": ["movie", "film", "picture", "flick"],
    "music": ["music", "melody", "tune", "harmony"],
    "mystery": ["mystery", "enigma", "puzzle", "riddle"],
    "name": ["name", "title", "label", "designation"],
    "night": ["night", "evening", "darkness", "nighttime"],
    "noise": ["noise", "sound", "racket", "din"],
    "object": ["object", "item", "thing", "entity"],
    "occasion": ["occasion", "event", "instance", "moment"],
    "office": ["office", "workplace", "workspace", "bureau"],
    "opinion": ["opinion", "view", "belief", "stance"],
    "order": ["order", "sequence", "arrangement", "directive"],
    "owner": ["owner", "holder", "possessor", "proprietor"],
    "package": ["package", "bundle", "parcel", "packet"],
    "pain": ["pain", "ache", "discomfort", "suffering"],
    "painting": ["painting", "artwork", "canvas", "masterpiece"],
    "parent": ["parent", "mother", "father", "guardian"],
    "partner": ["partner", "associate", "collaborator", "counterpart"],
    "passage": ["passage", "excerpt", "selection", "paragraph"],
    "passion": ["passion", "ardor", "fervor", "zeal"],
    "path": ["path", "track", "trail", "route"],
    "payment": ["payment", "fee", "charge", "remittance"],
    "phone": ["phone", "telephone", "handset", "receiver"],
    "phrase": ["phrase", "expression", "wording", "term"],
    "plant": ["plant", "vegetation", "flora", "greenery"],
    "power": ["power", "strength", "force", "might"],
    "practice": ["practice", "custom", "habit", "routine"],
    "prize": ["prize", "award", "trophy", "honor"],
    "profession": ["profession", "occupation", "career", "vocation"],
    "program": ["program", "software", "application", "app"],
    "proof": ["proof", "evidence", "verification", "documentation"],
    "property": ["property", "asset", "holding", "belonging"],
    "proposal": ["proposal", "suggestion", "recommendation", "proposition"],
    "protection": ["protection", "defense", "shielding", "safeguarding"],
    "quantity": ["quantity", "amount", "volume", "measure"],
    "race": ["race", "contest", "competition", "marathon"],
    "range": ["range", "scope", "span", "spectrum"],
    "reference": ["reference", "citation", "source", "mention"],
    "relationship": ["relationship", "connection", "bond", "association"],
    "requirement": ["requirement", "need", "necessity", "prerequisite"],
    "research": ["research", "investigation", "inquiry", "analysis"],
    "restaurant": ["restaurant", "eatery", "diner", "bistro"],
    "reward": ["reward", "prize", "accolade", "bounty"],
    "rival": ["rival", "competitor", "challenger", "contender", "opposition", "adversary"],
    "road": ["road", "street", "highway", "route"],
    "room": ["room", "space", "chamber", "quarter"],
    "salary": ["salary", "pay", "wage", "stipend"],
    "satisfaction": ["satisfaction", "contentment", "gratification", "fulfillment"],
    "scene": ["scene", "view", "sight", "vista"],
    "schedule": ["schedule", "timetable", "agenda", "itinerary"],
    "school": ["school", "academy", "institute", "college"],
    "secret": ["secret", "mystery", "confidence", "enigma"],
    "sense": ["sense", "feeling", "impression", "notion"],
    "sequence": ["sequence", "order", "series", "succession", "progression", "chain"],
    "shop": ["shop", "store", "retailer", "outlet"],
    "side": ["side", "edge", "border", "flank"],
    "sign": ["sign", "signal", "indicator", "mark"],
    "situation": ["situation", "circumstance", "state", "condition"],
    "skill": ["skill", "ability", "talent", "expertise"],
    "smell": ["smell", "scent", "aroma", "fragrance"],
    "software": ["software", "program", "application", "app"],
    "song": ["song", "tune", "melody", "anthem"],
    "sound": ["sound", "noise", "tone", "acoustic"],
    "source": ["source", "origin", "beginning", "wellspring"],
    "space": ["space", "room", "area", "expanse"],
    "speaker": ["speaker", "orator", "lecturer", "presenter"],
    "speech": ["speech", "address", "lecture", "discourse"],
    "staff": ["staff", "personnel", "workforce", "employees"],
    "stage": ["stage", "phase", "step", "point"],
    "statement": ["statement", "declaration", "assertion", "pronouncement"],
    "student": ["student", "pupil", "learner", "scholar"],
    "study": ["study", "research", "investigation", "inquiry"],
    "success": ["success", "achievement", "triumph", "victory"],
    "suggestion": ["suggestion", "proposal", "recommendation", "proposition"],
    "summer": ["summer", "season", "warmth", "solstice"],
    "surface": ["surface", "face", "exterior", "facade"],
    "symbol": ["symbol", "emblem", "token", "insignia"],
    "teacher": ["teacher", "instructor", "educator", "tutor"],
    "technology": ["technology", "innovation", "engineering", "tech"],
    "tendency": ["tendency", "trend", "inclination", "drift"],
    "theory": ["theory", "hypothesis", "notion", "conception"],
    "thing": ["thing", "object", "item", "entity"],
    "topic": ["topic", "subject", "theme", "focus"],
    "total": ["total", "sum", "aggregate", "whole"],
    "tour": ["tour", "trip", "visit", "excursion"],
    "trade": ["trade", "commerce", "business", "exchange"],
    "tradition": ["tradition", "custom", "heritage", "convention"],
    "training": ["training", "instruction", "coaching", "drill"],
    "treatment": ["treatment", "therapy", "remedy", "care"],
    "tree": ["tree", "timber", "sapling", "trunk"],
    "truth": ["truth", "fact", "reality", "verity"],
    "understanding": ["understanding", "comprehension", "grasp", "familiarity"],
    "vehicle": ["vehicle", "automobile", "transport", "conveyance"],
    "victim": ["victim", "casualty", "sufferer", "prey"],
    "village": ["village", "hamlet", "settlement", "commune"],
    "vision": ["vision", "dream", "aspiration", "foresight"],
    "warning": ["warning", "alert", "caution", "notice"],
    "wealth": ["wealth", "riches", "fortune", "assets"],
    "weapon": ["weapon", "arm", "instrument", "implement"],
    "weather": ["weather", "climate", "conditions", "elements"],
    "website": ["website", "site", "page", "portal"],
    "woman": ["woman", "female", "lady", "gentlewoman"],
    "word": ["word", "term", "vocabulary", "expression"],
    "worker": ["worker", "laborer", "employee", "hand"],
    "writer": ["writer", "author", "scribe", "novelist"],
}

# ---------------------------------------------------------------------------
# 中文同义词典（v0.4，配合 ZhAdapter 使用）
#
# 设计原则：
# 1. 词条统一为双字词（前向最大匹配分词的粒度一致性）
# 2. 组内声母种类 ≥3（KeyedLetterMap 洗牌后大概率可表达双 bit）
# 3. 组内词性一致、语义等价、常见语境可互换
# 4. 主词条唯一（同形词只保留一个组）
# 5. 无生造词——全部为现代汉语常用词
# ---------------------------------------------------------------------------

ZH_SYNONYMS_RAW: Dict[str, List[str]] = {
    # --- 形容词 ---
    "快速": ["快速", "迅速", "高效", "及时", "敏捷", "飞快"],
    "重要": ["重要", "关键", "主要", "紧要", "重大", "核心"],
    "优秀": ["优秀", "出色", "卓越", "杰出", "优异", "出众"],
    "简单": ["简单", "容易", "简便", "轻松", "浅显", "简明"],
    "复杂": ["复杂", "繁杂", "繁琐", "棘手", "艰难", "费解"],
    "强大": ["强大", "强盛", "雄厚", "坚强", "顽强", "壮实"],
    "脆弱": ["脆弱", "薄弱", "软弱", "虚弱", "单薄", "娇嫩"],
    "清晰": ["清晰", "清楚", "明白", "明了", "透彻", "明晰"],
    "模糊": ["模糊", "含糊", "隐约", "朦胧", "混浊", "迷离"],
    "稳定": ["稳定", "稳固", "牢靠", "平稳", "安定", "扎实"],
    "灵活": ["灵活", "机动", "敏捷", "变通", "灵巧", "活泛"],
    "安全": ["安全", "可靠", "稳妥", "保险", "平安", "稳固"],
    "危险": ["危险", "凶险", "危急", "可怕", "吓人", "惊险"],
    "新颖": ["新颖", "独创", "崭新", "别致", "新奇", "时髦"],
    "传统": ["传统", "惯例", "常规", "旧有", "沿袭", "古板"],
    "全面": ["全面", "完整", "系统", "周全", "齐备", "广泛"],
    "精确": ["精确", "精准", "准确", "严密", "细致", "无误"],
    "免费": ["免费", "无偿", "义务", "赠送", "白送", "分文"],
    "昂贵": ["昂贵", "高价", "奢侈", "豪华", "花钱", "破费"],
    "便宜": ["便宜", "廉价", "实惠", "低价", "省钱", "经济"],
    "方便": ["方便", "便利", "便捷", "省事", "顺手", "灵便"],
    "困难": ["困难", "艰难", "艰辛", "棘手", "不易", "为难"],
    "明显": ["明显", "显著", "突出", "醒目", "分明", "昭然"],
    "普通": ["普通", "平常", "一般", "寻常", "平凡", "普及"],
    "特别": ["特别", "特殊", "格外", "异常", "尤其", "独特"],
    "紧急": ["紧急", "迫切", "危急", "火速", "加急", "急迫"],
    "认真": ["认真", "仔细", "细心", "用心", "负责", "严谨"],
    "严格": ["严格", "严厉", "严苛", "较真", "刻板", "死板"],
    "友好": ["友好", "友善", "亲切", "和蔼", "热情", "和睦"],
    "谨慎": ["谨慎", "小心", "慎重", "留神", "提防", "戒备"],
    "聪明": ["聪明", "智慧", "机敏", "伶俐", "睿智", "精明"],
    "愚蠢": ["愚蠢", "愚笨", "迟钝", "笨拙", "呆板", "糊涂"],
    "积极": ["积极", "主动", "踊跃", "热心", "进取", "向上"],
    "消极": ["消极", "被动", "低迷", "颓废", "消沉", "丧气"],
    "成功": ["成功", "顺利", "告捷", "完满", "告成", "得手"],
    "失败": ["失败", "受挫", "落败", "告负", "失利", "挫败"],
    "满意": ["满意", "知足", "称心", "惬意", "顺心", "舒坦"],
    "失望": ["失望", "沮丧", "失落", "灰心", "泄气", "丧气"],
    "热情": ["热情", "热忱", "热心", "踊跃", "积极", "盛情"],
    "冷静": ["冷静", "沉着", "镇定", "平和", "理智", "淡定"],
    "秘密": ["秘密", "机密", "隐秘", "私密", "暗中", "保密"],
    "公开": ["公开", "透明", "公示", "公布", "开放", "明面"],
    "先进": ["先进", "前沿", "领先", "尖端", "一流", "超前"],
    "落后": ["落后", "滞后", "掉队", "过时", "陈旧", "老套"],
    "丰富": ["丰富", "丰盛", "充足", "多样", "繁多", "充实"],
    "短缺": ["短缺", "匮乏", "不足", "稀缺", "紧张", "告急"],
    "完美": ["完美", "完善", "圆满", "理想", "无瑕", "完好"],
    "粗糙": ["粗糙", "毛糙", "简陋", "草率", "马虎", "大略"],
    "精细": ["精细", "精巧", "精致", "考究", "讲究", "入微"],
    "流畅": ["流畅", "顺畅", "流利", "通顺", "连贯", "娴熟"],
    "生疏": ["生疏", "陌生", "生硬", "僵化", "呆滞", "别扭"],
    "巨大": ["巨大", "庞大", "宏伟", "浩大", "可观", "浩繁"],
    "微小": ["微小", "细小", "轻微", "渺小", "细微", "细碎"],
    "高效": ["高效", "高速", "快捷", "利落", "麻利", "迅速"],
    "美丽": ["美丽", "漂亮", "好看", "优美", "秀丽", "美观"],
    "丑陋": ["丑陋", "难看", "丑怪", "寒碜", "不堪", "拙劣"],
    "快乐": ["快乐", "开心", "高兴", "愉快", "欢喜", "愉悦"],
    "悲伤": ["悲伤", "伤心", "难过", "悲痛", "哀伤", "忧愁"],
    # --- 动词 ---
    "帮助": ["帮助", "协助", "支援", "帮忙", "扶助", "搭手"],
    "提高": ["提高", "提升", "增高", "抬升", "拔高", "攀高"],
    "降低": ["降低", "下降", "减少", "回落", "走低", "下调"],
    "改善": ["改善", "改进", "优化", "完善", "改良", "增进"],
    "支持": ["支持", "支撑", "援助", "扶植", "力挺", "后盾"],
    "反对": ["反对", "抵制", "抗拒", "驳斥", "否定", "驳倒"],
    "实现": ["实现", "达成", "完成", "落实", "兑现", "做到"],
    "开发": ["开发", "研制", "打造", "构建", "创设", "营建"],
    "设计": ["设计", "规划", "构想", "拟定", "草拟", "擘画"],
    "分析": ["分析", "解析", "剖析", "研判", "拆解", "推演"],
    "解决": ["解决", "处理", "化解", "排除", "攻克", "破解"],
    "创建": ["创建", "创立", "建立", "创办", "组建", "设立"],
    "管理": ["管理", "治理", "管制", "打理", "统管", "掌管"],
    "维护": ["维护", "保养", "维持", "守护", "护卫", "保育"],
    "更新": ["更新", "升级", "换代", "刷新", "修订", "改版"],
    "发布": ["发布", "公布", "颁布", "推出", "发表", "公示"],
    "推广": ["推广", "普及", "宣传", "推介", "传扬", "扩散"],
    "提供": ["提供", "供应", "供给", "给予", "奉献", "奉上"],
    "获取": ["获取", "取得", "获得", "得到", "收获", "揽取"],
    "保护": ["保护", "防护", "保卫", "守护", "捍卫", "拱卫"],
    "检测": ["检测", "检验", "监测", "排查", "核查", "查验"],
    "验证": ["验证", "证实", "确认", "核实", "查证", "印证"],
    "执行": ["执行", "施行", "实施", "践行", "履行", "落实"],
    "评估": ["评估", "评价", "估量", "衡量", "测评", "考量"],
    "整合": ["整合", "融合", "合并", "组合", "融汇", "融通"],
    "部署": ["部署", "配置", "安排", "布设", "调配", "铺排"],
    "监控": ["监控", "监视", "监测", "督导", "督查", "巡查"],
    "记录": ["记录", "记载", "登录", "登记", "录入", "摘录"],
    "传递": ["传递", "传达", "传送", "传输", "转达", "递送"],
    "展示": ["展示", "呈现", "显示", "表现", "展现", "显露"],
    "解释": ["解释", "说明", "阐释", "解读", "讲解", "阐明"],
    "建议": ["建议", "提议", "倡导", "主张", "倡议", "建言"],
    "取消": ["取消", "撤销", "撤回", "作废", "废除", "吊销"],
    "增加": ["增加", "增添", "添加", "扩充", "追加", "增补"],
    "删除": ["删除", "移除", "清除", "删去", "除去", "剔掉"],
    "修改": ["修改", "修正", "改动", "变更", "修订", "改写"],
    "启动": ["启动", "开启", "发动", "起动", "上线", "开动"],
    "停止": ["停止", "终止", "中止", "停顿", "叫停", "驻停"],
    "选择": ["选择", "挑选", "选取", "遴选", "甄选", "拣选"],
    "使用": ["使用", "运用", "利用", "采用", "应用", "借助"],
    "学习": ["学习", "研习", "钻研", "修习", "攻读", "苦读"],
    "培训": ["培训", "培养", "训练", "培育", "教导", "调教"],
    "沟通": ["沟通", "交流", "洽谈", "商谈", "对话", "通气"],
    "合作": ["合作", "协作", "配合", "联手", "合伙", "协同"],
    "竞争": ["竞争", "角逐", "较量", "争夺", "比拼", "竞逐"],
    "创造": ["创造", "发明", "首创", "开创", "独创", "原创"],
    "寻找": ["寻找", "搜寻", "查找", "搜索", "觅取", "探访"],
    "发现": ["发现", "发觉", "察觉", "识别", "看出", "窥见"],
    "理解": ["理解", "了解", "领会", "明白", "懂得", "通晓"],
    "应用": ["应用", "运用", "实践", "施行", "采用", "活用"],
    "控制": ["控制", "掌控", "操纵", "支配", "把握", "驾驭"],
    "引导": ["引导", "指引", "带领", "率领", "领路", "导引"],
    "推动": ["推动", "推进", "促进", "催生", "促成", "助推"],
    "防止": ["防止", "预防", "防范", "避免", "阻止", "杜绝"],
    "影响": ["影响", "作用", "波及", "牵动", "殃及", "触及"],
    "包含": ["包含", "包括", "含有", "涵盖", "囊括", "包罗"],
    "表示": ["表示", "表明", "示意", "彰显", "显露", "标示"],
    "认为": ["认为", "以为", "觉得", "主张", "笃信", "确信"],
    "希望": ["希望", "期望", "盼望", "期待", "渴求", "祈望"],
    "努力": ["努力", "尽力", "竭力", "奋力", "全力", "苦干"],
    "完成": ["完成", "做完", "办好", "了结", "收官", "告竣"],
    "开始": ["开始", "启动", "着手", "开头", "起步", "开动"],
    "结束": ["结束", "终结", "完结", "告终", "落幕", "收尾"],
    "继续": ["继续", "持续", "延续", "接续", "延伸", "相继"],
    "等待": ["等待", "等候", "守候", "静候", "期盼", "伫候"],
    "尝试": ["尝试", "试验", "试探", "试行", "试水", "摸底"],
    "避免": ["避免", "避开", "躲开", "规避", "绕行", "闪避"],
    # --- 名词 ---
    "系统": ["系统", "体系", "平台", "架构", "整体", "建制"],
    "产品": ["产品", "商品", "制品", "物件", "货品", "成品"],
    "服务": ["服务", "业务", "服侍", "照料", "接待", "效劳"],
    "功能": ["功能", "效能", "功用", "性能", "作用", "功效"],
    "用户": ["用户", "客户", "顾客", "主顾", "买家", "来客"],
    "团队": ["团队", "队伍", "集体", "班组", "阵营", "群组"],
    "公司": ["公司", "企业", "厂商", "商号", "店家", "机构"],
    "项目": ["项目", "工程", "课题", "事项", "专项", "任务"],
    "任务": ["任务", "工作", "作业", "差事", "职务", "活计"],
    "目标": ["目标", "目的", "指标", "标的", "靶向", "鹄的"],
    "结果": ["结果", "成果", "结局", "成效", "收效", "下场"],
    "过程": ["过程", "流程", "进程", "历程", "经过", "沿革"],
    "方法": ["方法", "办法", "方式", "途径", "手法", "招数"],
    "问题": ["问题", "难题", "疑问", "困惑", "症结", "麻烦"],
    "方案": ["方案", "对策", "举措", "主意", "计策", "谋略"],
    "原因": ["原因", "缘由", "成因", "起因", "根源", "来由"],
    "例子": ["例子", "实例", "案例", "示例", "样本", "范例"],
    "数据": ["数据", "资料", "信息", "材料", "记录", "数值"],
    "信息": ["信息", "消息", "资讯", "情报", "讯息", "音讯"],
    "报告": ["报告", "汇报", "呈报", "总结", "陈述", "通报"],
    "文件": ["文件", "文档", "材料", "文本", "卷宗", "案卷"],
    "请求": ["请求", "申请", "恳求", "诉求", "呈请", "吁请"],
    "响应": ["响应", "回应", "答复", "回复", "反馈", "回音"],
    "版本": ["版本", "版次", "版型", "批次", "刊行", "印次"],
    "风险": ["风险", "危险", "隐患", "危机", "险情", "风浪"],
    "收益": ["收益", "效益", "回报", "红利", "进账", "收成"],
    "成本": ["成本", "费用", "开支", "花销", "耗费", "本钱"],
    "价值": ["价值", "意义", "分量", "身价", "成色", "含意"],
    "质量": ["质量", "品质", "质地", "水准", "成色", "品级"],
    "速度": ["速度", "速率", "进度", "快慢", "时速", "节奏"],
    "时间": ["时间", "时段", "时期", "光阴", "工夫", "岁月"],
    "地点": ["地点", "场所", "位置", "处所", "方位", "所在"],
    "人员": ["人员", "成员", "职员", "员工", "人士", "一员"],
    "人们": ["人们", "大家", "众人", "民众", "大众", "群众"],
    "方式": ["方式", "形式", "模式", "形态", "样式", "款式"],
    "部分": ["部分", "局部", "片段", "板块", "区段", "枝节"],
    "数量": ["数量", "数目", "总量", "数额", "计量", "总数"],
    "程度": ["程度", "水平", "力度", "强度", "深度", "幅度"],
    "类型": ["类型", "种类", "类别", "门类", "品类", "型别"],
    "领域": ["领域", "范围", "界别", "范畴", "行当", "版图"],
    "行业": ["行业", "产业", "业界", "业态", "圈子", "行辈"],
    "世界": ["世界", "天下", "世间", "寰宇", "全球", "尘寰"],
    "未来": ["未来", "将来", "前景", "前途", "明天", "远景"],
    "过去": ["过去", "从前", "以往", "昔日", "往昔", "旧时"],
    "增长": ["增长", "提升", "扩充", "壮大", "攀升", "递增"],
    "语言": ["语言", "言语", "话语", "文辞", "措辞", "谈吐"],
    "网络": ["网络", "网路", "组网", "连网", "联网", "管网"],
    "引擎": ["引擎", "机芯", "核心", "主机", "动力", "机枢"],
    "模型": ["模型", "模式", "模板", "范本", "样板", "模子"],
    "工具": ["工具", "器具", "用具", "器械", "家什", "帮手"],
    "设备": ["设备", "装备", "器材", "装置", "机具", "设施"],
    "机器": ["机器", "机械", "机组", "机具", "器械", "机台"],
    "性能": ["性能", "效能", "表现", "能力", "功力", "实力"],
    "经验": ["经验", "阅历", "历练", "体会", "心得", "履历"],
    "环境": ["环境", "氛围", "处境", "场域", "境况", "周遭"],
    "结构": ["结构", "构造", "架构", "布局", "格局", "框架"],
    "目的": ["目的", "意图", "用意", "初衷", "本意", "旨趣"],
    "细节": ["细节", "细目", "琐节", "点滴", "微末", "枝叶"],
    "评论": ["评论", "评价", "点评", "评议", "品评", "论说"],
    "预算": ["预算", "经费", "拨款", "开支", "财源", "资金"],
    "进展": ["进展", "进度", "步伐", "脚步", "推进", "势头"],
    "洞察": ["洞察", "洞见", "见识", "眼光", "眼力", "识见"],
    "模式": ["模式", "范式", "套路", "路数", "章法", "打法"],
    "选项": ["选项", "备选", "候选", "可选", "出路", "备取"],
    "策略": ["策略", "战略", "对策", "方略", "计谋", "谋略"],
    "技术": ["技术", "工艺", "技艺", "技巧", "技能", "手艺"],
    "研究": ["研究", "钻研", "探究", "探讨", "考究", "求索"],
    "教学": ["教学", "授课", "讲课", "育人", "传道", "授业"],
    "写作": ["写作", "撰稿", "执笔", "著述", "书写", "笔耕"],
    "阅读": ["阅读", "阅览", "浏览", "研读", "翻阅", "披览"],
    "会议": ["会议", "会谈", "集会", "大会", "例会", "碰头"],
    "活动": ["活动", "行动", "举措", "运作", "事宜", "事项"],
    "计划": ["计划", "规划", "打算", "设想", "安排", "部署"],
    "决策": ["决策", "决断", "拍板", "定夺", "裁定", "抉择"],
    "领导": ["领导", "领袖", "首领", "头领", "主管", "掌门"],
    "员工": ["员工", "职员", "雇员", "同僚", "部下", "下属"],
    "客户": ["客户", "顾客", "买家", "主顾", "客商", "买主"],
    "市场": ["市场", "市面", "行市", "商圈", "销路", "市况"],
    "机会": ["机会", "机遇", "时机", "契机", "良机", "机缘"],
    "挑战": ["挑战", "考验", "难关", "难题", "险阻", "关卡"],
    "需求": ["需求", "需要", "诉求", "所求", "期许", "盼头"],
    "资源": ["资源", "资产", "储备", "家底", "存量", "本源"],
    "内容": ["内容", "实质", "内涵", "要义", "要旨", "精髓"],
    "形式": ["形式", "形态", "样态", "款式", "式样", "格式"],
    "标准": ["标准", "规范", "准则", "基准", "标尺", "圭臬"],
    "规则": ["规则", "规矩", "章法", "条例", "章程", "细则"],
    "流程": ["流程", "程序", "工序", "环节", "步骤", "次序"],
    "能力": ["能力", "本领", "才干", "实力", "功力", "才略"],
    "责任": ["责任", "义务", "职责", "本分", "担当", "使命"],
    "利益": ["利益", "好处", "益处", "效益", "红利", "实惠"],
    "损失": ["损失", "亏损", "损害", "折损", "亏空", "损耗"],
    "效率": ["效率", "效能", "产出", "产能", "效益", "功用"],
    "效果": ["效果", "成效", "效用", "功效", "成果", "战果"],
    "观点": ["观点", "看法", "见解", "主张", "立场", "视角"],
    "态度": ["态度", "姿态", "立场", "神态", "口吻", "架势"],
    "情绪": ["情绪", "心情", "心境", "心态", "心思", "感触"],
    "感受": ["感受", "体会", "体验", "感触", "心得", "领悟"],
    "想法": ["想法", "念头", "主意", "点子", "构思", "盘算"],
    "知识": ["知识", "学识", "学问", "常识", "见闻", "智识"],
    "技能": ["技能", "本事", "手艺", "专长", "特长", "绝活"],
    "文化": ["文化", "文明", "人文", "教化", "文脉", "风气"],
    "教育": ["教育", "教导", "培育", "培养", "训诫", "启智"],
    "健康": ["健康", "康健", "安康", "体魄", "体格", "身子"],
    "生活": ["生活", "日子", "生计", "日常", "起居", "度日"],
    "工作": ["工作", "活计", "差事", "事务", "业务", "差务"],
    "业务": ["业务", "事务", "营生", "行当", "主业", "本行"],
    "组织": ["组织", "机构", "团体", "集体", "建制", "序列"],
    "机构": ["机构", "单位", "部门", "院所", "团体", "班底"],
    "部门": ["部门", "科室", "单位", "处室", "分部", "部室"],
    "中心": ["中心", "核心", "中枢", "重心", "中央", "轴心"],
    "重点": ["重点", "要点", "重心", "焦点", "主旨", "要项"],
    "基础": ["基础", "根基", "底子", "根底", "基石", "底座"],
    "核心": ["核心", "中心", "要害", "命脉", "中枢", "内核"],
    "关键": ["关键", "要害", "命门", "枢纽", "症结", "关窍"],
    "概念": ["概念", "观念", "理念", "范畴", "界说", "义涵"],
    "理论": ["理论", "学说", "原理", "论说", "学理", "公理"],
    "实践": ["实践", "实操", "施行", "行动", "躬行", "践行"],
    "创新": ["创新", "革新", "变革", "突破", "开拓", "求新"],
    "发展": ["发展", "进展", "演进", "成长", "壮大", "拓展"],
    "变化": ["变化", "变动", "改变", "变迁", "演变", "更动"],
    "状态": ["状态", "状况", "情形", "态势", "气象", "格局"],
    "情况": ["情况", "状况", "情形", "事态", "境况", "实情"],
    "条件": ["条件", "前提", "要件", "依据", "凭据", "倚仗"],
    "因素": ["因素", "要素", "因子", "成因", "动因", "缘由"],
    "特征": ["特征", "特点", "特性", "特质", "品性", "秉性"],
    "优势": ["优势", "长处", "强项", "优胜", "上风", "优点"],
    "劣势": ["劣势", "短处", "弱项", "短板", "下风", "缺点"],
    "缺陷": ["缺陷", "瑕疵", "毛病", "漏洞", "破绽", "缺憾"],
    "改进": ["改进", "改善", "提升", "完善", "精进", "革新"],
    "突破": ["突破", "攻克", "打破", "冲破", "突围", "破解"],
    "保障": ["保障", "保证", "确保", "捍卫", "护佑", "保住"],
    "防控": ["防控", "防范", "管控", "戒备", "提防", "布防"],
    "平台": ["平台", "载体", "基座", "底盘", "依托", "舞台"],
    "反馈": ["反馈", "回应", "回音", "反应", "回复", "答覆"],
    "清单": ["清单", "名册", "名录", "目录", "台账", "簿册"],
}


def validate_dictionary(
    groups: Dict[str, List[str]],
    single_word: bool = True,
) -> None:
    """词典完整性自检（构建/测试期调用，嵌入路径不调用）。

    检查项：
    - 主词条必须出现在自己的候选组里（保证查询命中）
    - 组内无重复词
    - 无跨组共享词（稳定化管线依赖词的唯一归属）
    - 单词约束（single_word=True 时禁止空格/连字符）
    - 组大小 ≥2（单词组无替换能力）

    Raises:
        ValueError: 描述第一个发现的问题
    """
    seen: Dict[str, str] = {}
    for key, cands in groups.items():
        if key not in cands:
            raise ValueError(f"主词条 '{key}' 不在自己的候选组中")
        if len(set(cands)) != len(cands):
            raise ValueError(f"组 '{key}' 内有重复词: {cands}")
        if len(set(cands)) < 2:
            raise ValueError(f"组 '{key}' 只有 {len(set(cands))} 个词，无替换能力")
        for w in set(cands):
            if single_word and (" " in w or "-" in w):
                raise ValueError(f"词条 '{w}'（组 '{key}'）违反单词约束")
            if w in seen and seen[w] != key:
                raise ValueError(
                    f"词条 '{w}' 跨组共享: '{seen[w]}' 与 '{key}'"
                )
            seen.setdefault(w, key)
